title: Listen
description: "Testing punctuation and markup for audible variances in screen readers."
url: "https://doublegreat.dev"
baseurl: /listen

author:
  name: "@double-great"

github: double-great/listen

remote_theme: double-great/great-great-jekyll-theme@v1.0.0

permalink: /:title/

header_pages:
  - related-resources.md

custom_head: |
  <script src="https://cdn.plyr.io/3.6.2/plyr.js"></script>

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:title/
  - scope:
      path: "test"
    values:
      layout: "test"
      permalink: /:basename/test/

collections:
  cases:
    output: true

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - Gemfile
  - Gemfile.lock
  - .github
  - library.dic
  - vendor
