title: Listen
description: "Testing punctuation and markup for audible variances in screen readers."
url: "https://doublegreat.dev"
baseurl: /listen

theme: minima
show_excerpts: true

author:
  name: "@double-great"

github: double-great/listen

permalink: /:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:title/
  - scope:
      path: "test"
    values:
      layout: "test"
      permalink: /:basename/test/

collections:
  cases:
    output: true

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - Gemfile
  - Gemfile.lock
  - .github
  - library.dic
